version: "3.5"

services:

  react-app:
    container_name: demo-react
    build:
      context: .
      dockerfile: Dockerfile
    image: colmedo/reactapp
    ports: 
      - 3000:3000
    volumes:
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:demo.carlosdev.fr"
      - "traefik.docker.network=web"

networks:
  web:
    external: true  